server:
  port: 8766

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jd?serverTimezone=CTT
    username: root
    password: yanwenqiang

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

